[config]
schemaVerison = "0.0.1"

[general]
repository = "https://thunderstore.io"

[package]
namespace = "Rune580"
name = "REPO_SteamNetworking"
description = "API/Library for networking using Steamworks socket relays."
websiteUrl = "https://github.com/Rune580/RepoSteamNetworking"
containsNsfwContent = false

[package.dependencies]
BepInEx-BepInExPack = "5.4.2100"

[build]
icon = "icons/icon.png"
readme = "../README.md"
outdir = "../dist"

[[build.copy]]
source = "../RepoSteamNetworking/bin/Release/netstandard2.1/RepoSteamNetworking.dll"
target = "plugins/RepoSteamNetworking/"

[[build.copy]]
source = "../RepoSteamNetworking/bin/Release/netstandard2.1/RepoSteamNetworking.pdb"
target = "plugins/RepoSteamNetworking/"

[[build.copy]]
source = "../CHANGELOG.md"
target = "/"

[[build.copy]]
source = "../LICENSE"
target = "/"

[publish]
communities = [ "repo" ]

[publish.categories]
repo = [ "mods", "libraries" ]